services:
  # Web Service
  - type: web
    name: stock-analyzer
    runtime: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: DATABASE_URL
        fromDatabase:
          name: stock-analyzer-db
          property: connectionString

databases:
  # PostgreSQL Database
  - name: stock-analyzer-db
    databaseName: hai_assignment3
    user: hai_assignment3_user
    plan: free
    ipAllowList: []